version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01

    steps:
      - checkout

      - run:
          name: docker push
          command: |
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            docker build . -t mrflick72/i18n-messages-k8s:snapshot
            docker push mrflick72/i18n-messages-k8s:snapshot